tasks:
  install:
    image: cypress/browsers
    command:
      - yarn
    args:
      - install
  lint:
    image: cypress/browsers
    command:
      - yarn
    args:
      - lint
  cypress:
    image: cypress/browsers
    command:
      - yarn
    args:
      - test
  a11y-test:
    image: cypress/browsers
    command:
      - yarn
    args:
      - a11y-test

workflow:
  - install
  - sail:parallel:
      - lint
      - cypress
      - a11y-test
