tasks:
  build:
    image: node:carbon
    command:
      - yarn
    args:
      - install
  prettier:
    image: node:carbon
    command:
      - yarn
    args:
      - prettier
  lint:
    image: node:carbon
    command:
      - yarn
    args:
      - lint
