tasks:
  install:
    image: cypress/browsers
    command:
      - yarn
    args:
      - install
  lint:
    image: cypress/browsers
    command:
      - yarn
    args:
      - lint
  cypress:
    image: cypress/browsers
    command: 
      - yarn
    args:
      - test

workflow:
  - install
  - sail:parallel:
      - lint
      - cypress
